name: deploy_to_firebase_hosting
on:
  push:
    branches:
      - master

jobs:
  deploy_to_firebase_hosting:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      - name: Setup node and build
        uses: actions/setup-node@master
        with:
          node-version: '10.x'
      - run: npm install
      - run: npm run build-storybook
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting --project enhancers-design-sistem
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ENHANCERS_DESIGN_SISTEM }}
